"""Create user table

Revision ID: 9d351dbc6e48
Revises: 
Create Date: 2024-10-02 14:31:49.801441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d351dbc6e48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=80), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('contact', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('years', sa.String(length=128), nullable=False),
    sa.Column('month', sa.String(length=128), nullable=False),
    sa.Column('day', sa.String(length=128), nullable=False),
    sa.Column('genre', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('firstname'),
    sa.UniqueConstraint('lastname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
